latte_redis_server.o: latte_redis_server.c latte_redis_server.h \
 redis_command.h client.h robj/robj.h libs/zmalloc/zmalloc.h \
 ../deps/jemalloc/include/jemalloc/jemalloc.h libs/sds/sds.h \
 libs/assert/assert.h libs/assert/../util/util.h \
 libs/assert/../util/sha256.h libs/connection/connection.h \
 libs/connection/../sds/sds.h libs/connection/anet.h libs/connection/ae.h \
 libs/connection/monotonic.h libs/connection/../fmacros.h \
 libs/list/list.h libs/rax/rax.h libs/dict/dict.h libs/dict/mt19937-64.h \
 db.h libs/util/util.h libs/util/sha256.h libs/log/log.h \
 libs/crc64/crc64.h
redis_command.o: redis_command.c
